version: '3'
services:
  web:
    # image: tvelocity/etherpad-lite
    # build: .
    image: shioju/etherpad-docker-prebuilt
    depends_on:
      - db
    environment:
      ETHERPAD_DB_HOST: db
      ETHERPAD_DB_PASSWORD: password
      ETHERPAD_ADMIN_USER: admin
      ETHERPAD_ADMIN_PASSWORD: password
    volumes:
      - ./data/settings:/opt/etherpad-lite/var
    ports:
      - "9001:9001"
  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - ./data/mysql:/var/lib/mysql
